spin_manifest_version = 2

[application]
name = "http-in"
version = "1.0.0"
authors = ["Jora Troosh <tensorush@gmail.com>"]
description = "Example application that serves an inbound HTTP request."

[[trigger.http]]
route = "/..."
component = "http-in"

[component.http-in]
source = "../../zig-out/bin/http-in.wasm"

[component.http-in.build]
workdir = "../../"
command = "zig build example"
