version = "1.0.0"
name = "spin-http-zig"
spin_manifest_version = "1"
trigger = { type = "http", base = "/" }
authors = ["Jora Troosh <tensorush@gmail.com>"]
description = "Example application that serves an inbound HTTP request."

[[component]]
id = "spin_http_zig"
source = "../../zig-out/bin/http-in.wasm"

[component.build]
command = "zig build example"
workdir = "../../"

[component.trigger]
route = "/..."
