spin_manifest_version = 2

[application]
name = "config"
version = "1.0.0"
authors = ["Jora Troosh <tensorush@gmail.com>"]
description = "Example application that reads a config message."

[variables]
object = { default = "codebase" }

[[trigger.http]]
route = "/..."
component = "config"

[component.config]
source = "../../zig-out/bin/config.wasm"

[component.config.build]
workdir = "../../"
command = "zig build example"

[component.config.variables]
message = "All your {{object}} are belong to us!"
