version = "1.0.0"
name = "spin-config-zig"
spin_manifest_version = "1"
trigger = { type = "http", base = "/" }
authors = ["Jora Troosh <tensorush@gmail.com>"]
description = "Example application that reads a config message."

[variables]
object = { default = "codebase" }

[[component]]
id = "spin_config_zig"
source = "../../zig-out/bin/config.wasm"

[component.build]
command = "zig build example"
workdir = "../../"

[component.config]
message = "All your {{object}} are belong to us"

[component.trigger]
route = "/..."
