version = "0.1.0"
name = "{{name}}"
authors = ["{{authors}}"]
spin_manifest_version = "1"
description = "{{description}}"
trigger = { type = "http", base = "{{base}}" }

[[component]]
id = "{{kebab-case-name}}"
allowed_http_hosts = []
source = "main.wasm"

[component.trigger]
executor = { type = "wagi" }
route = "{{http-path}}"

[component.build]
command = "zig build-exe -O ReleaseSmall -target wasm32-wasi src/main.zig"
watch = ["src/**/*.zig"]
