spin_manifest_version = 2

[application]
name = "sqlite"
version = "1.0.0"
authors = ["Jora Troosh <tensorush@gmail.com>"]
description = "Example application that reads a SQLite message."

[[trigger.http]]
route = "/..."
component = "sqlite"

[component.sqlite]
source = "../../zig-out/bin/sqlite.wasm"

[component.sqlite.build]
workdir = "../../"
command = "zig build example"
